wandb_version: 1

BS:
  desc: null
  value: 2048
_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    code_path: code/ParT/Part_wandb_train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
    start_time: 1675883589.471625
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 3
      - 55
      3:
      - 1
      - 15
      - 16
      - 23
      4: 3.6.9
      5: 0.13.7
      8:
      - 5
embed_dim:
  desc: null
  value: 128
lr_mult:
  desc: null
  value: 0.3
lr_rate:
  desc: null
  value: 0.005
num_enc:
  desc: null
  value: 3
num_epochs:
  desc: null
  value: 50
num_head:
  desc: null
  value: 8
