executable              = sing.sh
arguments               = $(ClusterId)$(ProcId)
output                  = sing.$(ClusterId).$(ProcId).out
error                   = sing.$(ClusterId).$(ProcId).err
log                     = sing.$(ClusterId).log

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT

request_GPUs = 1
request_CPUs = 8
request_disk = 5GB

requirements = regexp("A100", TARGET.CUDADeviceName)
+JobFlavour = "nextweek"
queue
